name: Build Android APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Android
      uses: android-actions/setup-android@v3
      
    - name: Install Android Platform
      run: |
        sdkmanager "platforms;android-30"
        sdkmanager "build-tools;30.0.3"
        
    - name: Create debug keystore
      run: |
        keytool -genkey -v -keystore debug.keystore -alias androiddebugkey -storepass android -keypass android -keyalg RSA -keysize 2048 -validity 10000 -dname "CN=Android Debug,O=Android,C=US"
        
    - name: Build APK
      run: |
        rustup target add aarch64-linux-android
        cargo install cargo-apk
        cargo apk build -p phira --release
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: phira-mod
        path: target/android-artifacts/release/apk/*.apk
